### ISSUE TITLE
Poor contrast in the gutter for the current line

### ISSUE THREAD

**Issue by brainplot** [belak/emacs-monokai-pro-theme#5]
![Screenshot_20191116_030403](https://user-images.githubusercontent.com/28014843/68986279-f70b2d00-081d-11ea-926b-177650aae653.png)

There's very poor contrast in the gutter for the current line number, to the point where it's barely visible. It's more cognitive load than necessary having to work out the current line number based on the previous/next line.

Thank you very much for this port! I'm trying to switch to Emacs from Sublime and this theme is making me feel already at home :slightly_smiling_face:
Adding the other flavors as well would be awesome, since I was using Spectrum on Sublime.

**Comment by belak** [comment]
There have been some tweaks to the gutter and I'm not sure this is an issue any longer. If you're still having trouble, definitely let me know and I'll try to investigate more.

Also, the flavors were added earlier tonight!

**Comment by brainplot** [comment]
Thanks! I'm no longer using Emacs but I'll definitely check out your theme again if I ever decide to give the editor another go!
