### ISSUE TITLE
 Symbol’s value as variable is void: monokai-pro-spectrum-theme-colors

### ISSUE THREAD

**Issue by voltaireodactyl** [belak/emacs-monokai-pro-theme#6]
I've recently started getting the following error since updating to 27, and I cannot for the life of me figure out how to fix it:

>  Symbol’s value as variable is void: monokai-pro-spectrum-theme-colors

Same for the other flavors of the theme. A weirder thing is I tried to roll back to 26 and it still doesn't work. Is anybody else experiencing this issue? Thx

**Comment by voltaireodactyl** [comment]
I closed this because I wasn't sure this was the right fork -- but now it appears to be the correct one. Apologies for the abject confusion, I'm fairly new at this. Previously I had been using this in my init:

>(use-package monokai-pro-theme
  :ensure t
  :init
  (load-theme 'monokai-pro t))
(monokai-pro-theme-set-faces 'monokai-pro monokai-pro-spectrum-theme-colors monokai-pro-faces)

But now I'm getting that variable is void error no matter what I try. Any help would be hugely appreciated.

**Comment by belak** [comment]
This package didn't have those colors defined until today. If you're still having trouble after updating, please feel free to file a new issue. Thanks!
